name: Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry
        poetry install --with dev,lint --no-root
    - name: Run test [pytest]
      run: |
        poetry run pytest --cov --cov-report xml:coverage/coverage.xml
    - name: Store coverage files
      uses: actions/upload-artifact@v3
      with:
        name: coverage
        path: coverage